#pragma config(Sensor, S2,     colorSensor,    sensorEV3_Color)
#pragma config(Motor,  motorA,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool done = false;
bool fB = false;
bool mTC = false;
bool mTT = false;

bool x = true;
bool y = false;
int xTargetValue = 0;
int yTargetValue = 0;
TLegoColors currentColor;
int blueCount = 0;
int sleepValue = 2000;
int redCount = 0;
bool origin = true;

task moveFromButton()
{
	repeatUntil(done == true)
	{
		if(getButtonPress(buttonEnter) == 1)
		{
			done = true;
		}
		if(getButtonPress(buttonRight) == 1)
		{
			if(x == true)
			{
				if(xTargetValue < 4)
				{
					xTargetValue = xTargetValue + 1;
					sleep(200);
				}
			}
			if(y == true)
			{
				if(yTargetValue < 2)
				{
					yTargetValue = yTargetValue + 1;
					sleep(200);
				}
			}
		}
		if(getButtonPress(buttonLeft) == 1)
		{
			if(x == true)
			{
				if(xTargetValue > 0)
				{
					xTargetValue = xTargetValue - 1;
					sleep(200);
				}
			}
			if(y == true)
			{
				if(yTargetValue > 0)
				{
					yTargetValue = yTargetValue - 1;
					sleep(200);
				}
			}
		}
		if(getButtonPress(buttonUp) == 1)
		{
			if(x == false)
			{
				y = false;
				x = true;
			}
		}
		if(getButtonPress(buttonDown) == 1)
		{
			if(y == false)
			{
				x = false;
				y = true;
			}
		}

		if(x == true)
		{
			displayBigTextLine(1, "%d  Set X", xTargetValue);
			displayBigTextLine(3, "%d", yTargetValue);
			displayBigTextLine(5, "Press Enter");
			displayBigTextLine(7, "Button to");
			displayBigTextLine(9, "Start");
		}
		if(y == true)
		{
			displayBigTextLine(1, "%d", xTargetValue);
			displayBigTextLine(3, "%d  Set Y", yTargetValue);
			displayBigTextLine(5, "Press Enter");
			displayBigTextLine(7, "Button to");
			displayBigTextLine(9, "Start");
		}
	}
}

task findBlueGoBlack()
{
	repeatUntil(fB == true)
	{
		currentColor = getColorName(S2);
		if(currentColor == colorRed)
		{
			setMotorSync(right, left, 0, 0);
			sleep(sleepValue);
			setMotorSync(right, left, 0, -10);
			sleep(sleepValue);
			setMotorSync(right, left, 0, 0);
			sleep(sleepValue);
			setMotorSync(right, left, 100, 10);
			sleep(1700);
			setMotorSync(right, left, 0, 0);
		}
		else if(currentColor == colorBlack)
		{
			setMotorSync(right, left, 0, 0);
			sleep(sleepValue);
			setMotorSync(right, left, 0, -10);
			sleep(sleepValue);
			setMotorSync(right, left, 0, 0);
			sleep(sleepValue);
			setMotorSync(right, left, 100, 10);
			sleep(1700);
			setMotorSync(right, left, 0, 0);
			fB = true;
		}
		else if(currentColor == colorBlue)
		{
			blueCount = blueCount + 1;
			sleep(1000);
		}
		else
		{
			setMotorSync(right, left, 0, 10);
			displayBigTextLine(1, "%d  Blue", blueCount);
		}
		sleep(10);
	}
}

task moveToCorner()
{
	repeatUntil(mTC == true)
	{
		currentColor = getColorName(S2);
		if(currentColor == colorBlack)
		{
			setMotorSync(right, left, 0, 0);
			sleep(sleepValue);
			setMotorSync(right, left, 0, -10);
			sleep(sleepValue);
			setMotorSync(right, left, 0, 0);
			sleep(sleepValue);
			setMotorSync(right, left, 100, 10);
			sleep(3400);
			setMotorSync(right, left, 0, 0);
			mTC = true;
		}
		else if(currentColor == colorRed)
		{
			redCount = redCount + 1;
			sleep(1000);
		}
		else
		{
			setMotorSync(right, left, 0, 10);
			displayBigTextLine(1, "%d  Red", redCount);
		}
		sleep(10);
	}
}

void ifOrigin()
{
	displayBigTextLine(1, "Origin");
	if(yTargetValue == 2 && blueCount == 0)
	{
		origin = false;
		displayBigTextLine(1, "Not Origin");
	}
	if(yTargetValue == 0 && blueCount > 0)
	{
		origin = false;
		displayBigTextLine(1, "Not Origin");
	}
	if(xTargetValue < 2 && redCount > 1)
	{
		origin = false;
		displayBigTextLine(1, "Not Origin");
	}
	if(xTargetValue > 2 && redCount < 2)
	{
		origin = false;
		displayBigTextLine(1, "Not Origin");
	}
	blueCount = -1;
	redCount = -1;
}

task moveToTarget()
{
	if(origin == false)
	{
		xTargetValue = 4 - xTargetValue;
		yTargetValue = 2 - yTargetValue;
	}
	bool xAxis = false;
	repeatUntil(xAxis == true)
	{
		if(xTargetValue == redCount)
		{
			setMotorSync(right, left, 0, 0);
			sleep(sleepValue);
			setMotorSync(right, left, 0, -10);
			sleep(sleepValue);
			setMotorSync(right, left, 0, 0);
			sleep(sleepValue);
			setMotorSync(right, left, -100, 10);
			sleep(1700);
			setMotorSync(right, left, 0, 0);
			xAxis = true;
		}
		displayBigTextLine(1, "White");
		currentColor = getColorName(S2);
		if(currentColor == colorRed)
		{
			displayBigTextLine(1, "Red");
			redCount = redCount + 1;
			sleep(1000);
		}
		else if(currentColor == colorBlack)
		{
			displayBigTextLine(1, "Black");
			setMotorSync(right, left, 0, 0);
			sleep(sleepValue);
			setMotorSync(right, left, 0, -10);
			sleep(sleepValue);
			setMotorSync(right, left, 0, 0);
			sleep(sleepValue);
			setMotorSync(right, left, -100, 10);
			sleep(1700);
			setMotorSync(right, left, 0, 0);
			xAxis = true;
		}
		else
		{
			setMotorSync(right, left, 0, 10);
		}
		sleep(10);
	}
	bool yAxis = false;
	repeatUntil(yAxis == true)
	{
		if(yTargetValue == blueCount)
		{
			setMotorSync(right, left, 0, 0);
			sleep(sleepValue);
			setMotorSync(right, left, 0, -10);
			sleep(sleepValue);
			setMotorSync(right, left, 0, 0);
			yAxis = true;
		}
		currentColor = getColorName(S2);
		displayBigTextLine(1, "White");
		if(currentColor == colorBlue)
		{
			displayBigTextLine(1, "Blue");
			blueCount = blueCount + 1;
			sleep(1000);
		}
		else if(currentColor == colorBlack)
		{
			displayBigTextLine(1, "Black");
			setMotorSync(right, left, 0, 0);
			sleep(sleepValue);
			setMotorSync(right, left, 0, -10);
			sleep(sleepValue);
			setMotorSync(right, left, 0, 0);
			xAxis = true;
		}
		else
		{
			setMotorSync(right, left, 0, 10);
		}
		sleep(10);
	}
	mTT = true;
}

task main()
{
	startTask(moveFromButton);
	repeatUntil(done == true)
	{
		sleep(10);
	}
	displayBigTextLine(1, "");
	displayBigTextLine(3, "");
	displayBigTextLine(5, "");
	displayBigTextLine(7, "");
	displayBigTextLine(9, "");
	startTask(findBlueGoBlack);
	repeatUntil(fB == true)
	{
		sleep(10);
	}
	sleep(1000);

	startTask(moveToCorner);
	repeatUntil(mTC == true)
	{
		sleep(10);
	}

	ifOrigin();
	sleep(2000);

	done = false;
	xTargetValue = 0;
	yTargetValue = 0;
	x = true;
	y = false;
	startTask(moveFromButton);
	repeatUntil(done == true)
	{
		sleep(10);
	}
	displayBigTextLine(1, "");
	displayBigTextLine(3, "");
	displayBigTextLine(5, "");
	displayBigTextLine(7, "");
	displayBigTextLine(9, "");
	startTask(moveToTarget);
	repeatUntil(mTT == true)
	{
		sleep(10);
	}
}
